apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  # ClusterIP — only reachable inside the cluster.
  # Traefik ingress routes external traffic to this service.
  type: {{ .Values.service.type }}
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
